import { HttpBody, UrlParams } from '@effect/platform'
import { Effect, Schema } from 'effect'
import { DiscoveryInformationResponseSchema } from '../schema/rest'
import { makeEndpoint } from '../matrix-endpoint'

const CommonOptionsSchema = Schema.Struct({
  initialDeviceDisplayName: Schema.optional(Schema.String).pipe(Schema.fromKey('initial_device_display_name')),
  refreshToken: Schema.optional(Schema.Boolean).pipe(Schema.fromKey('refresh_token')),
})

export const postLoginV3OptionsSchema = Schema.Union(
  Schema.Struct({
    type: Schema.Literal('m.login.token'),
    token: Schema.String,
  }).pipe(Schema.extend(CommonOptionsSchema)),
  Schema.Struct({
    type: Schema.Literal('m.login.password'),
    password: Schema.String,
    identifier: Schema.Union(
      Schema.Struct({ type: Schema.Literal('m.id.user'), user: Schema.String }),
      Schema.Record({ key: Schema.String, value: Schema.Unknown }),
    ),
  }).pipe(Schema.extend(CommonOptionsSchema)),
)

export const postLoginV3ResponseSchema = Schema.Struct({
  accessToken: Schema.propertySignature(Schema.String).pipe(Schema.fromKey('access_token')),
  deviceId: Schema.propertySignature(Schema.String).pipe(Schema.fromKey('device_id')),
  userId: Schema.propertySignature(Schema.String).pipe(Schema.fromKey('user_id')),
  expiresInMs: Schema.optional(Schema.Number.pipe(Schema.int())).pipe(Schema.fromKey('expires_in_ms')),
  refreshToken: Schema.optional(Schema.String).pipe(Schema.fromKey('refresh_token')),
  wellKnown: Schema.optional(DiscoveryInformationResponseSchema).pipe(Schema.fromKey('well_known')),
})

/**
 * `GET /_matrix/client/v3/login`
 *
 * Authenticates the user, and issues an access token they can use to authorize themself in subsequent requests.
 *
 * If the client does not supply a device_id, the server must auto-generate one.
 *
 * The returned access token must be associated with the device_id supplied by the client or generated by the server. The server may
 * invalidate any access token previously associated with that device. See [Relationship between access tokens and
 * devices](https://spec.matrix.org/v1.17/client-server-api/#relationship-between-access-tokens-and-devices).
 *
 * @category Endpoints
 * @see https://spec.matrix.org/v1.17/client-server-api/#post_matrixclientv3login
 */
export const postLoginV3 = (options: Schema.Schema.Type<typeof postLoginV3OptionsSchema>) =>
  makeEndpoint({
    auth: false,
    method: 'POST',
    path: '/v3/login',
    body: Schema.encode(postLoginV3OptionsSchema)(options).pipe(Effect.andThen(HttpBody.json)),
    schema: postLoginV3ResponseSchema,
  })
